TIBS.stem.Web/Models/Layout/HeaderViewModel.cs
using System.Collections.Generic;
using Abp.Application.Navigation;
using Abp.Localization;
using TIBS.stem.Sessions.Dto;

namespace TIBS.stem.Web.Models.Layout
{
    public class HeaderViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }
        
        public IReadOnlyList<LanguageInfo> Languages { get; set; }

        public LanguageInfo CurrentLanguage { get; set; }
        
        public UserMenu Menu { get; set; }
        
        public string CurrentPageName { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public string GetShownLoginName()
        {
            if (!IsMultiTenancyEnabled)
            {
                return LoginInformations.User.UserName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + LoginInformations.User.UserName
                : LoginInformations.Tenant.TenancyName + "\\" + LoginInformations.User.UserName;
        }
    }
}

TIBS.stem.Web/Controllers/ApplicationController.cs
using System.Web.Mvc;
using Abp.Auditing;
using Abp.Web.Mvc.Authorization;

namespace TIBS.stem.Web.Controllers
{
    [AbpMvcAuthorize]
    public class ApplicationController : stemControllerBase
    {
        [DisableAuditing]
        public ActionResult Index()
        {
            return View("~/App/common/views/layout/layout.cshtml"); //Layout of the angular application.
        }
    }
}

TIBS.stem.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration.Startup;
using Abp.Threading;
using TIBS.stem.Sessions;
using TIBS.stem.Web.Models.Layout;
using TIBS.stem.Web.Navigation;

namespace TIBS.stem.Web.Controllers
{
    /// <summary>
    /// Layout for 'front end' pages.
    /// </summary>
    public class LayoutController : stemControllerBase
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public LayoutController(ISessionAppService sessionAppService, IUserNavigationManager userNavigationManager, IMultiTenancyConfig multiTenancyConfig)
        {
            _sessionAppService = sessionAppService;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
        }

        [ChildActionOnly]
        public PartialViewResult Header(string currentPageName = "")
        {
            var headerModel = new HeaderViewModel();
            
            if (AbpSession.UserId.HasValue)
            {
                headerModel.LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations());
            }

            headerModel.Languages = LocalizationManager.GetAllLanguages();
            headerModel.CurrentLanguage = LocalizationManager.CurrentLanguage;
            
            headerModel.Menu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync(AppNavigationProvider.FrontendMenuName, AbpSession.UserId));
            headerModel.CurrentPageName = currentPageName;

            headerModel.IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled;

            return PartialView("~/Views/Layout/_Header.cshtml", headerModel);
        }
    }
}

TIBS.stem.Web/Views/Layout/_Footer.cshtml
@using Abp.Timing
    <!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <!-- BEGIN COPYRIGHT -->
            <div class="col-md-6 col-sm-6 padding-top-10">
                @Clock.Now.Year © stem. ALL Rights Reserved. <a href="javascript:;">Privacy Policy</a> | <a href="javascript:;">Terms of Service</a>
            </div>
            <!-- END COPYRIGHT -->
            <!-- BEGIN PAYMENTS -->
            <div class="col-md-6 col-sm-6">
                <ul class="social-footer list-unstyled list-inline pull-right">
                    <li><a href="javascript:;"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-dribbble"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-skype"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-github"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-youtube"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-dropbox"></i></a></li>
                </ul>
            </div>
            <!-- END PAYMENTS -->
        </div>
    </div>
</div>
<!-- END FOOTER -->

TIBS.stem.Web/Views/Layout/_Header.cshtml
@using Abp.Application.Navigation
@using Abp.Collections.Extensions
@using Abp.Extensions
@using TIBS.stem.Web.Views
@model TIBS.stem.Web.Models.Layout.HeaderViewModel
@helper ShowMenuItemRecursively(UserMenuItem menuItem, int currentLevel)
{
    <li class="@(menuItem.Name == Model.CurrentPageName ? "active" : "") @(menuItem.Items.IsNullOrEmpty() ? "" : (currentLevel == 0 ? "dropdown" : "dropdown-submenu"))">
        @if (menuItem.Items.IsNullOrEmpty())
        {
            if (!menuItem.Url.IsNullOrEmpty())
            {
                <a href="@(UrlChecker.IsRooted(menuItem.Url) ? menuItem.Url : (ApplicationPath + menuItem.Url))">@menuItem.DisplayName</a>
            }
            else
            {
                <a href="@ApplicationPath">@menuItem.DisplayName</a>
            }
        }
        else
        {
            <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">
                @menuItem.DisplayName
            </a>
            <ul class="dropdown-menu">
                @foreach (var childMenuItem in menuItem.Items)
                {
                    @ShowMenuItemRecursively(childMenuItem, currentLevel + 1)
                }
            </ul>
        }
    </li>
}
<div class="pre-header">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 additional-shop-info">
                <ul class="list-unstyled list-inline">
                    <li><i class="fa fa-phone"></i><span>+1 456 6717</span></li>
                    <li><i class="fa fa-envelope-o"></i><span>info@mydomain.com</span></li>
                </ul>
            </div>
            <div class="col-md-6 col-sm-6 additional-nav">
                <ul class="list-unstyled list-inline pull-right">
                    @if (Model.Languages.Count > 1)
                    {
                        <li>
                            <ul id="TopLanguageList">
                                @foreach (var language in Model.Languages)
                                {
                                    <li class="@(language.Name == Model.CurrentLanguage.Name ? "selected-language" : "")">
                                        <a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@Request.Url"><i class="@language.Icon"></i> <span>@language.DisplayName</span></a>
                                    </li>
                                }
                            </ul>
                        </li>
                    }
                    <li>
                        @if (Model.LoginInformations != null)
                        {
                            <a href="@Url.Action("Index", "Application")">@Model.GetShownLoginName() (@L("GoToApplication"))</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Login", "Account")">@L("LogIn")</a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="header">
    <div class="container">
        <a class="site-logo" href="@Url.Action("Index", "Home")">
            <img src="~/App/common/images/app-logo-on-light.png" alt="" width="168" height="33"/>
        </a>
        <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>
        <div class="header-navigation pull-right font-transform-inherit">
            <ul>
                @foreach (var menuItem in @Model.Menu.Items)
                {
                    @ShowMenuItemRecursively(menuItem, 0)
                }
            </ul>
        </div>
    </div>
</div>

TIBS.stem.Web/Views/Layout/_Layout.cshtml
@using System.Web.Optimization
@using Abp.Web.Mvc.Extensions
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title>stem</title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    @* Fill these meta tags upon your project specification *@
    <meta content="stem" name="description">
    <meta content="stem" name="keywords">
    <meta content="stem" name="author">

    @* You can enable and fill these lines according to documentation on http://ogp.me/
    <meta property="og:site_name" content="-CUSTOMER VALUE-">
    <meta property="og:title" content="-CUSTOMER VALUE-">
    <meta property="og:description" content="-CUSTOMER VALUE-">
    <meta property="og:type" content="website">
    <meta property="og:image" content="-CUSTOMER VALUE-">
    <meta property="og:url" content="-CUSTOMER VALUE-">*@

    <link rel="shortcut icon" href="~/favicon.ico">

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css">

    @Styles.Render("~/Bundles/Frontend/libs/css")
    @RenderSection("Styles", false)
    @Styles.Render("~/Bundles/Frontend/metronic/css")
    @Styles.Render("~/Bundles/Common/css")

    @Html.IncludeStyle("~/Views/Layout/layout.css")

    <script type="text/javascript">
        @* This is used to get the application's root path from javascript.
        It's useful if you're running application in a virtual directory under IIS. *@
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

</head>
<body class="corporate">

    @Html.Action("Header", "Layout", new { currentPageName = ViewBag.CurrentPageName })

    <div class="main">
        <div class="container">
            @RenderBody()
        </div>
    </div>

    @Html.Partial("~/Views/Layout/_Footer.cshtml")

    <!--[if lt IE 9]>
        <script src="~/libs/respond/respond.min.js"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/Frontend/libs/js")

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/AbpScripts/GetScripts" type="text/javascript"></script>

    @Scripts.Render("~/Bundles/Frontend/metronic/js")

    @Scripts.Render("~/Bundles/Common/js")

    <script type="text/javascript">
        $(function () {
            Layout.init();
        });
    </script>

    @RenderSection("Scripts", false)

</body>

</html>

TIBS.stem.Web/Views/Layout/_PreFooter.cshtml
    <!-- BEGIN PRE-FOOTER -->
<div class="pre-footer">
    <div class="container">
        <div class="row">
            <!-- BEGIN BOTTOM ABOUT BLOCK -->
            <div class="col-md-4 col-sm-6 pre-footer-col">
                <h2>About us</h2>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam sit nonummy nibh euismod tincidunt ut laoreet dolore magna aliquarm erat sit volutpat.</p>
                <div class="photo-stream">
                    <h2>Photos Stream</h2>
                    <ul class="list-unstyled">
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/people/img5-small.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img1.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/people/img4-large.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img6.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img3.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/people/img2-large.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img2.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img5.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/people/img5-small.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img1.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/people/img4-large.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img6.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img3.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/people/img2-large.jpg"></a></li>
                        <li><a href="javascript:;"><img alt="" src="~/metronic/assets/frontend/pages/img/works/img2.jpg"></a></li>
                    </ul>
                </div>
            </div>
            <!-- END BOTTOM ABOUT BLOCK -->
            <!-- BEGIN BOTTOM CONTACTS -->
            <div class="col-md-4 col-sm-6 pre-footer-col">
                <h2>Our Contacts</h2>
                <address class="margin-bottom-40">
                    35, Lorem Lis Street, Park Ave<br>
                    California, US<br>
                    Phone: 300 323 3456<br>
                    Fax: 300 323 1456<br>
                    Email: <a href="mailto:info@mydomain.com">info@mydomain.com</a><br>
                    Skype: <a href="skype:metronic">myskypename</a>
                </address>
                <div class="pre-footer-subscribe-box pre-footer-subscribe-box-vertical">
                    <h2>Newsletter</h2>
                    <p>Subscribe to our newsletter and stay up to date with the latest news and deals!</p>
                    <form action="#">
                        <div class="input-group">
                            <input type="text" placeholder="youremail@mail.com" class="form-control">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">Subscribe</button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            <!-- END BOTTOM CONTACTS -->
            <!-- BEGIN TWITTER BLOCK -->
            <div class="col-md-4 col-sm-6 pre-footer-col">
                <h2 class="margin-bottom-0">Latest Tweets</h2>
                <a class="twitter-timeline" href="https://twitter.com/twitterapi" data-tweet-limit="2" data-theme="dark" data-link-color="#57C8EB" data-widget-id="455411516829736961" data-chrome="noheader nofooter noscrollbar noborders transparent">Loading tweets by @@keenthemes...</a>
            </div>
            <!-- END TWITTER BLOCK -->
        </div>
    </div>
</div>
<!-- END PRE-FOOTER -->